### ISSUE TITLE
dep-selector-libgecode apparently installs incorrectly with rvm gemsets

### ISSUE THREAD

**Issue by danielsdeleo** [chef/dep-selector-libgecode#20]
Copied from the bug report here: https://github.com/opscode/dep-selector/issues/23#issuecomment-41701467

**Comment by sathlan** [comment]
Hi,

on centos7 using this Gemfile:
```ruby
source 'https://rubygems.org'
gem 'vagrant-wrapper'
gem 'berkshelf'
gem 'kitchen-vagrant', '~> 0.17.0.dev'
```

followed by `bundle exec kitchen list`, I got:

```
Message: Could not load or activate Berkshelf (Could not open library '/home/chem/.gem/ruby/gems/dep_selector-1.0.3/lib/dep_gecode.so': libgecodeset.so.32: cannot open shared object file: No such file or directory
```

The libraries are there:
```shell
ruby -rpp -rdep-selector-libgecode -e 'pp Dir[DepSelectorLibgecode.opt_path + "/*"]'
["/home/chem/.gem/ruby/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/lib/libgecodeset.so.32.0",
 "~/.gem/ruby/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/lib/libgecodeint.so",
 "~/.gem/ruby/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/lib/libgecodeint.so.32",
...
```

If I run bundler like this:

```shell
$ LD_LIBRARY_PATH=~/.gem/ruby/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/lib/ bundle exec kitchen list 
```
then it works.

The only relevant system modification is 
```shell
sudo alternatives --set ld /usr/bin/ld.gold
```
Furthermore the gecode* packages are not available for centos 7, so I'm kinda stuck with the strange LD_LIBRARY_PATH.

Did I missed something ?

**Comment by RumataEstor** [comment]
```
$ readelf -a ~/.gem/ruby/2.2.0/gems/dep_selector-1.0.3/lib/dep_gecode.so|grep OS/ABI
  OS/ABI:                            UNIX - System V
$ readelf -a ~/.gem/ruby/2.2.0/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/lib/libgecodeset.so.32|grep OS/ABI
  OS/ABI:                            UNIX - GNU
```
Does it makes any difference?

**Comment by dbafast** [comment]
OSX
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Could not load or activate Berkshelf (Could not open library '/Library/Ruby/Gems/2.0.0/gems/dep_selector-1.0.3/lib/dep_gecode.bundle': dlopen(/Library/Ruby/Gems/2.0.0/gems/dep_selector-1.0.3/lib/dep_gecode.bundle, 5): Library not loaded: /private/var/folders/q6/_4hvkps50mvdwgq1kq35x_000000gr/T/bundler20151023-6196-1t2v8ysdep-selector-libgecode-1.0.2/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/lib/libgecodesearch.32.dylib

**Comment by lamont-granquist** [comment]
So I've been using rvm gemsets on OSX and dep-selector-libgecode for years and have not run into issues.

There is an obvious problem we currently have which is that `brew install gecode` followed by trying to install with `USE_SYSTEM_GECODE=1` will fail because we lack bindings to libgecode 4.x

If people are having issues, they probably need to open up a new issue and provide COMPLETE examples of how their system is configured, what gecode libraries are installed on their system and how they're trying to go about building.  Right now I can't see enough in any of these examples to suggest what might have been broken and it seems like a mish-mash of different bugs.
